## Menus: Menu.conf
#

## MENUS
## Menu Styling

MenuStyle * MenuColorset 0, ActiveColorset 1, GreyedColorset 7, TitleColorset 10
MenuStyle * Hilight3DOff, HilightBack, HilightTitleBack, SeparatorsLong
MenuStyle * TrianglesSolid, TrianglesUseFore
MenuStyle * Font "xft:Noto:Sans:size=11"
MenuStyle * ItemFormat "%|%4.2i%5.3l%5.3>%|"
MenuStyle * BorderWidth 1

## Titlebar Right Click >> Send To
## Pager modules include page settings

DestroyMenu MenuWindowOps
AddToMenu   MenuWindowOps
+ "Resize " Resize
+ "----" Nop
+ "Move to... "
+ "   Web Desk  " MoveToDesk 0 0
+ "   Email Desk " MoveToDesk 0 1
+ "   Office Desk  " MoveToDesk 0 2
+ "   Misc Desk  " MoveToDesk 0 3
